#!/usr/bin/env python3

# -*- mode: python-mode -*-

import json
import sys

def list_contains(sublist, superlist):
    return all([item in superlist for item in sublist])

def sources_contains(subsource, supersource):
    return (
        subsource['root'] == supersource['root']
        and
        list_contains(subsource['files'], supersource['files'])
        and
        list_contains(subsource['files-under-root'],
                      supersource['files-under-root'])
        and
        list_contains(
            [name
             for name in subsource['all-files']
             if name.startswith(subsource['root'])],
            [name
             for name in supersource['all-files']
             if name.startswith(supersource['root'])]
        )
    )

def parse_json(name):
    with open(name) as data:
        return json.load(data)

def main():
    build = parse_json(sys.argv[1])
    find = parse_json(sys.argv[2])
    walk = parse_json(sys.argv[3])

    if not sources_contains(build, find):
        exit(1)
    if not sources_contains(build, walk):
        exit(2)
    if not sources_contains(find, walk):
        exit(3)
    if not sources_contains(walk, find):
        exit(4)
    exit(0)

if __name__ == '__main__':
    main()

