################################################################
# CBMC build layers

FROM cbmc

ENV VIEWER_SOURCE=/tmp/viewer-source
ENV VIEWER_STAGING=/tmp/viewer-staging
ENV VIEWER_INSTALL=/usr/local

ENV VIEWER_GITHUB=https://github.com/awslabs/aws-viewer-for-cbmc.git

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="America/New_York"
ENV PATH="/usr/local/bin:/usr/local/cbmc-viewer:${PATH}"
ENV PS1="viewer:\w "

RUN echo PS1=\"${PS1}\" >> /root/.bashrc

# install runtime dependencies
RUN \
  apt update && apt install -y \
    ctags \
    python-is-python3 \
    python3 \
    python3-pip
RUN python3 -m pip install voluptuous jinja2

# stage viewer
RUN \
  git clone ${VIEWER_GITHUB} ${VIEWER_SOURCE} && \
  cp -RP ${VIEWER_SOURCE} ${VIEWER_STAGING} && \
  rm -rf ${VIEWER_STAGING}/.git ${VIEWER_STAGING}/__pycache__

#################################################################
## CBMC viewer build layers
#
#FROM ubuntu:20.04 AS viewer-build
#
## install build dependencies
#RUN \
#  apt update && apt install -y \
#    git \
#  && rm -rf /var/lib/apt/lists/*
#
#RUN \
#  git clone https://github.com/awslabs/aws-viewer-for-cbmc.git /tmp/viewer && \
#  mkdir /tmp/viewer-install && \
#  cp -r /tmp/viewer/* /tmp/viewer-install


#################################################################
## Runtime layers
#
#FROM ubuntu:20.04
#
#ENV DEBIAN_FRONTEND="noninteractive"
#ENV TZ="America/New_York"
#
## install runtime dependencies
#RUN \
#  apt update && apt install -y \
#    cmake \
#    ctags \
#    g++ \
#    git \
#    make \
#    ninja-build \
#    python-is-python3 \
#    python3 \
#    python3-pip \
#  && rm -rf /var/lib/apt/lists/*
#RUN python3 -m pip install voluptuous jinja2
#
#COPY --from=cbmc-build ${ENV_STAGING}/ ${ENV_STAGING}/
#COPY --from=viewer-build /tmp/viewer-install/ /tmp/viewer-install/
#
#RUN \
#  mkdir /usr/local/cbmc-viewer && \
#  cp -R ${ENV_STAGING}/* /usr/local && \
#  cp -R /tmp/viewer-install/* /usr/local/cbmc-viewer && \
#  rm -rf ${ENV_STAGING} /tmp/viewer-install
#
#ENV PATH="/usr/local/bin:/usr/local/cbmc-viewer:${PATH}"
#ENV PS1="cbmc:\w "
#

#################################################################
## CBMC viewer build layers
#
#FROM ubuntu:20.04 AS viewer-build
#
## install build dependencies
#RUN \
#  apt update && apt install -y \
#    git \
#  && rm -rf /var/lib/apt/lists/*
#
#RUN \
#  git clone https://github.com/awslabs/aws-viewer-for-cbmc.git /tmp/viewer && \
#  mkdir /tmp/viewer-install && \
#  cp -r /tmp/viewer/* /tmp/viewer-install
