H_ENTRY = IsDHCPSocket
H_CBMCFLAGS = --unwind 1
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_DHCP.goto
H_EXPECTED = SUCCESSFUL

include ../../Makefile.common