################################################################
# CBMC build layers

FROM ubuntu:20.04 AS build

ENV VIEWER_SOURCE=/tmp/viewer-source
ENV VIEWER_STAGING=/tmp/viewer-staging
ENV VIEWER_INSTALL=/usr/local/cbmc-viewer

ENV VIEWER_GITHUB=https://github.com/awslabs/aws-viewer-for-cbmc.git

# build
ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="America/New_York"
RUN \
  apt update && apt install -y \
    git \
  && rm -rf /var/lib/apt/lists/*

# stage and install
RUN \
  git clone ${VIEWER_GITHUB} ${VIEWER_SOURCE} && \
  mkdir -p ${VIEWER_STAGING} && \
  cp -RP ${VIEWER_SOURCE}/* ${VIEWER_STAGING} && \
  rm -rf ${VIEWER_STAGING}/.git* ${VIEWER_STAGING}/__pycache__ && \
  mkdir -p ${VIEWER_INSTALL} && \
  cp -RP ${VIEWER_STAGING}/* ${VIEWER_INSTALL}

################################################################
# CBMC runtime layers

FROM ubuntu:20.04

VOLUME ["/home"]

ENV VIEWER_SOURCE=/tmp/viewer-source
ENV VIEWER_STAGING=/tmp/viewer-staging
ENV VIEWER_INSTALL=/usr/local/cbmc-viewer

ENV PATH="/usr/local/bin:/usr/local/cbmc-viewer:${PATH}"
ENV PS1="viewer:\w "

RUN echo PS1=\"${PS1}\" >> /root/.bashrc

# runtime dependencies
RUN \
  apt update && apt install -y \
    ctags \
    python-is-python3 \
    python3 \
    python3-pip \
  && rm -rf /var/lib/apt/lists/*
RUN python3 -m pip install voluptuous jinja2

# install
COPY --from=build ${VIEWER_STAGING} ${VIEWER_STAGING}
RUN \
  mkdir -p ${VIEWER_INSTALL} && \
  cp -RP ${VIEWER_STAGING}/* ${VIEWER_INSTALL}
