################################################################
# build layers

FROM ubuntu:20.04

ENV CBMC_SOURCE=/tmp/cbmc-source
ENV CBMC_STAGING=/tmp/cbmc-staging
ENV CBMC_INSTALL=/usr/local

ENV DESTDIR=${CBMC_STAGING}

ENV DEBIAN_FRONTEND="noninteractive"
ENV TZ="America/New_York"
ENV PATH="/usr/local/bin:/usr/local/cbmc-viewer:${PATH}"
ENV PS1="cbmc:\w "

RUN echo PS1=\"${PS1}\" >> /root/.bashrc

# install build dependencies
RUN \
  apt update && apt install -y \
    bison \
    cmake \
    flex \
    g++ \
    git \
    jq \
    libxml2-utils \
    maven \
    ninja-build \
    python-is-python3 \
    python3 \
    python3-pip

# stage cbmc
COPY . ${CBMC_SOURCE}
RUN \
  cd ${CBMC_SOURCE} && \
  rm -rf build && \
  git submodule update --init && \
  cmake -S. -Bbuild -GNinja && \
  cd build && ninja install

#  ctest -j4 -L CORE --output-on-failure && \
