#!/usr/bin/env python3

# -*- mode: python-mode -*-

"""Gather names of source files used to buid a goto binary."""

import json
import argparse
import logging

import make_sources

################################################################
# Argument parsing

def create_parser():
    """Build the command line parser."""

    parser = argparse.ArgumentParser(
        description='Scan a cbmc project for source files.')

    parser.add_argument(
        '--builddir',
        metavar='DIR',
        default='.',
        help="""
	The build directory.
	The command "make GOTO_CC=goto-cc cbmc"
        in this directory should build the cbmc goto binary.
	"""
    )
    parser.add_argument(
        '--srcdir',
        metavar='DIR',
        default='.',
        help="""
        The root of the source tree.
        The build directory is usually under the root
        of the source tree,
        but it doesn't have to be.
        """
    )
    parser.add_argument(
        '--merge',
        metavar='FILE',
        nargs='+',
        help="""
        A list of files produced by this program to merge
        into a single file (a summary).
        """
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Verbose output'
    )
    parser.add_argument(
        '--debug',
        action='store_true',
        help='Debugging output'
    )
    return parser

def main():
    """Gather names of source files used to buid a goto binary."""

    args = create_parser().parse_args()
    if args.verbose:
        logging.basicConfig(level=logging.INFO)
    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    if args.merge:
        print(json.dumps(make_sources.merge(args.merge), indent=2))
        exit()

    print(json.dumps(make_sources.source_files(args.builddir, args.srcdir),
                     indent=2))

if __name__ == '__main__':
    main()
