#!/usr/bin/env python3

# Emacs python mode
# -*- mode: python-mode -*-

import logging
import argparse
import make_reachable
import json

def create_parser():
    """Build the command line parser."""

    parser = argparse.ArgumentParser(
        description='List the reachable functions in a goto binary.')

    parser.add_argument(
        '--goto',
        metavar='GOTO',
        required=True,
        help="""
        The goto binary.
	"""
    )
    parser.add_argument(
        '--verbose',
        action='store_true',
        help='Verbose output'
    )
    parser.add_argument(
        '--debug',
        action='store_true',
        help='Debugging output'
    )
    return parser


def main():
    args = create_parser().parse_args()
    if args.verbose:
        logging.basicConfig(level=logging.INFO)
    if args.debug:
        logging.basicConfig(level=logging.DEBUG)

    reachable = make_reachable.reachable_functions(args.goto)
    print(json.dumps(reachable, indent=2))

if __name__ == '__main__':
    main()

