H_ENTRY = SendEventToIPTask
H_CBMCFLAGS = --unwind 1 --nondet-static
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_IP.goto $(FREERTOS)/freertos_kernel/tasks.goto
H_EXPECTED = SUCCESSFUL

include ../../Makefile.common