H_ENTRY = CheckOptions
H_CBMCFLAGS = --unwind 1 --unwindset prvCheckOptions.0:41
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_WIN.goto $(FREERTOS)/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_TCP_IP.goto $(FREERTOS)/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_Stream_Buffer.goto $(FREERTOS)/freertos_kernel/tasks.goto $(FREERTOS)/freertos_kernel/list.goto
H_ABSTRACTIONS = 
H_BUFFER_SIZE = 100
H_UNWIND_GOTO = 0
H_DEF = -DBUFFER_SIZE=100
H_EXPECTED = SUCCESSFUL

include ../Makefile.common