H_ENTRY = ClearARP
H_CBMCFLAGS = --unwind 1
H_OBJS = $(ENTRY)_harness.goto $(FREERTOS)/libraries/freertos_plus/standard/freertos_plus_tcp/source/FreeRTOS_ARP.goto
H_DEF = 
H_EXPECTED = SUCCESSFUL

include ../../Makefile.common